env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
plugins:
  - react
rules: {
  "react/react-in-jsx-scope": off,
  "@typescript-eslint/strict-boolean-expressions": off,
}
