version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysqldatavol:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f /kakei/tmp/pids/server.pid && bundle install && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/kakei
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  mysqldatavol:
